sample-php-laravel-app/app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

/* Tenant Routes */

// PreAuth
Route::get('/', function () { return Redirect::to('/auth/login' ); });
Route::get('/login/{portal_namespace?}', 'Auth\AuthController@login');
Route::controllers(['auth' => 'Auth\AuthController', 'password' => 'Auth\PasswordController', ]);

// Users
Route::get('users/verify/{token}', 'UsersController@verify');
Route::get('users/invite/{token}', 'UsersController@invite');
Route::post('users/invited/{token}', 'UsersController@invited');
Route::post('users/{id}/reinvite', 'UsersController@reinvite');
Route::get('users/profile', function() { return redirect(route('users.edit', Auth::user()->id)); });
Route::get('users/dashboard', 'UsersController@dashboard');
Route::put('users/toggle/{id}', 'UsersController@toggle');
Route::get('users/myprofile', function() {
	return redirect('users/' . Auth::user()->id . '/edit');
});

// Accounts
Route::get('accounts/profile', function() { return redirect(route('accounts.edit', Auth::user()->account_id)); });
Route::get('accounts/{id}/users', 'AccountsController@users');
Route::get('accounts/{id}/files', 'AccountsController@files');

// Messages
Route::group(['prefix' => 'messages'], function () {
    Route::get('/', ['as' => 'messages', 'uses' => 'MessagesController@index']);
    Route::get('/read_all', ['as' => 'messages.read_all', 'uses' => 'MessagesController@read_all']);
    Route::get('create', ['as' => 'messages.create', 'uses' => 'MessagesController@create']);
    Route::post('/', ['as' => 'messages.store', 'uses' => 'MessagesController@store']);
    Route::get('{id}', ['as' => 'messages.show', 'uses' => 'MessagesController@show']);
    Route::put('{id}', ['as' => 'messages.update', 'uses' => 'MessagesController@update']);
});

// Reservations
Route::get('reservations/calendars', 'ReservationsController@calendars');
Route::get('reservations/events', 'ReservationsController@events');

// Calendars
Route::get('calendars/reserve', 'CalendarsController@reserve');

// Comments
Route::get('comments/{id}/post', 'CommentsController@post');

// Likes
Route::post('likes/{id}/{type}', 'LikesController@unlike');

// Invoices
Route::get('invoices/download/{invoice_id}', 'InvoicesController@download');
Route::get('invoices/see/{invoice_id}', 'InvoicesController@see');

// PaymentAccounts
Route::get('payment_accounts/method/{type}', 'PaymentAccountsController@method');
Route::put('payment_accounts/primary/{id}', 'PaymentAccountsController@primary');
Route::put('payment_accounts/autopay', 'PaymentAccountsController@update_autopay');
Route::get('payment_accounts/autopay', 'PaymentAccountsController@autopay');

// RecurringPayments
Route::put('recurring_payments/subtotal', 'RecurringPaymentsController@subtotal');

// Message
Route::get('keys/email/{token}', 'KeysController@email');

// Resourceful
Route::resource('reservations', 'ReservationsController');
Route::resource('messages', 'MessagesController');
Route::resource('spaces', 'SpacesController');
Route::resource('accounts', 'AccountsController');
Route::resource('users', 'UsersController');
Route::resource('tags', 'TagsController');
Route::resource('posts', 'PostsController');
Route::resource('pages', 'PagesController');
Route::resource('comments', 'CommentsController');
Route::resource('files', 'FilesController');
Route::resource('likes', 'LikesController');
Route::resource('invoices', 'InvoicesController');
Route::resource('payment_accounts', 'PaymentAccountsController');
Route::resource('payments', 'PaymentsController');
Route::resource('recurring_payments', 'RecurringPaymentsController');

// Entrust User
// Entrust::routeNeedsRole('invoices*', ['member_owner', 'member_admin'], Redirect::to('/'), false);
Entrust::routeNeedsRole('payment_accounts*', ['member_owner', 'member_admin'], Redirect::to('/'), false);
Entrust::routeNeedsRole('payments*', ['member_owner', 'member_admin'], Redirect::to('/'), false);
Entrust::routeNeedsRole('recurring_payments*', ['member_owner', 'member_admin'], Redirect::to('/'), false);


/* Admin Routes */
Route::group(array('prefix' => 'admin', 'namespace' => 'Admin'), function()
{

	// Users
	Route::patch('users/assign', 'AdminUsersController@assign');
	Route::put('users/role_update/{id}', 'AdminUsersController@role_update');
	Route::get('users/myprofile', function() {
		return redirect('admin/users/' . Auth::user()->id . '/edit');
	});
	Route::get('users/{id}/notes', 'AdminUsersController@notes');
	Route::post('users/{id}/reinvite', 'AdminUsersController@reinvite');
	// Accounts
	Route::get('accounts/my_account', 'AdminAccountsController@edit');
	Route::get('accounts/spaces', 'AdminAccountsController@spaces');
	Route::get('accounts/invoices', 'AdminAccountsController@invoices');
	Route::get('accounts/payments', 'AdminAccountsController@payments');
	Route::patch('accounts/make_primary', 'AdminAccountsController@makePrimary');
	Route::get('accounts/{id}/users', 'AdminAccountsController@users');
	Route::get('accounts/{id}/accounting', 'AdminAccountsController@accounting');
	Route::get('accounts/{id}/notes', 'AdminAccountsController@notes');
	Route::get('accounts/{id}/files', 'AdminAccountsController@files');
	Route::put('accounts/toggle/{id}', 'AdminAccountsController@toggle');
	// Spaces
	Route::get('spaces/create_many', 'AdminSpacesController@createMany');
	Route::get('spaces/{id}/notes', 'AdminSpacesController@notes');
	Route::put('spaces/assign/{id}', 'AdminSpacesController@assign');
	// Reservations
	Route::get('reservations/calendars', 'AdminReservationsController@calendars');
	// Calendars
	Route::get('calendars/reserve', 'AdminCalendarsController@reserve');
	// Portals
	Route::get('portals/preauth_preview', 'AdminPortalsController@preauth_preview');
	Route::get('portals/manage', 'AdminPortalsController@edit');
	Route::get('portals/payments', 'AdminPortalsController@payments');
	Route::post('portals/portal_update', 'AdminPortalsController@portal_update');
	Route::get('portals/calendars', 'AdminPortalsController@calendars');
	Route::get('portals/accounting', 'AdminPortalsController@accounting');
	Route::get('portals/customize', 'AdminPortalsController@customize');
	// Dashboard
	Route::get('dashboards/preview', 'AdminDashboardsController@preview');
	Route::get('dashboards/reset', 'AdminDashboardsController@reset');
	// Quickbooks
	// App OAuth
	Route::get('quickbooks/appauth', 'AdminQuickbooksController@appauth');	
	Route::get('quickbooks/appauthed', 'AdminQuickbooksController@appauthed');	
	Route::get('quickbooks/qboauth', 'AdminQuickbooksController@qboauth');	
	Route::get('quickbooks/qboauthed', 'AdminQuickbooksController@qboauthed');	
	Route::get('quickbooks/disconnect', 'AdminQuickbooksController@disconnect');
	// Customers
	Route::get('quickbooks/customers', 'AdminQuickbooksController@customers');
	Route::post('quickbooks/customer_create/{quickbooks_customer_id}','AdminQuickbooksController@customer_create');
	Route::post('quickbooks/customer_delete/{quickbooks_customer_id}','AdminQuickbooksController@customer_delete');
	Route::post('quickbooks/customer_update/{quickbooks_customer_id}','AdminQuickbooksController@customer_update');
	Route::post('quickbooks/customer_sync/{quickbooks_customer_id}','AdminQuickbooksController@customer_sync');
	Route::post('quickbooks/create_quickbooks_customer/{account_id}', 'AdminQuickbooksController@create_quickbooks_customer');
	Route::post('quickbooks/update_quickbooks_customer/{account_id}', 'AdminQuickbooksController@update_quickbooks_customer');
	// Invoices
	Route::get('invoices/download/{invoice_id}', 'AdminInvoicesController@download');
	Route::post('invoices/email/{invoice_id}', 'AdminInvoicesController@email');
	// Recurring Invoices
	Route::post('recurring_invoices/toggle/{id}', 'AdminRecurringInvoicesController@toggle');
	Route::get('recurring_invoices/interval', 'AdminRecurringInvoicesController@interval');
	// Payments
	Route::post('payments/check/{transaction_id}', 'AdminPaymentsController@check');
	Route::post('payments/void/{transaction_id}', 'AdminPaymentsController@void');
	// PaymentAccounts
	Route::get('payment_accounts/method/{type}', 'AdminPaymentAccountsController@method');
	Route::put('payment_accounts/primary/{type}', 'AdminPaymentAccountsController@primary');
	// Resourceful
	Route::resource('calendars', 'AdminCalendarsController');
	Route::resource('reservations', 'AdminReservationsController');
	Route::resource('spaces', 'AdminSpacesController');
	Route::resource('portals', 'AdminPortalsController');
	Route::resource('accounts', 'AdminAccountsController');
	Route::resource('users', 'AdminUsersController');
	Route::resource('tags', 'AdminTagsController');
	Route::resource('pages', 'AdminPagesController');
	Route::resource('notes', 'AdminNotesController');
	Route::resource('messages', 'AdminMessagesController');
	Route::resource('dashboards', 'AdminDashboardsController');
	Route::resource('keys', 'AdminKeysController');
	Route::resource('payments', 'AdminPaymentsController');
	Route::resource('payment_accounts', 'AdminPaymentAccountsController');
	Route::resource('invoices', 'AdminInvoicesController');
	Route::resource('files', 'AdminFilesController');
	Route::resource('emails', 'AdminEmailsController');
	Route::resource('recurring_invoices', 'AdminRecurringInvoicesController');
	Route::resource('recurring_payments', 'AdminRecurringPaymentsController');
});

// Entrust Admin
Entrust::routeNeedsRole('portals/edit', ['portal_admin','portal_owner','root'], Redirect::to('/'), false);
Entrust::routeNeedsRole('admin/spaces*', ['portal_employee','portal_admin','portal_owner','root'], Redirect::to('/'), false);

sample-php-laravel-app/app/User.php
<?php

namespace App;

use DB;
use Carbon\Carbon;
use Illuminate\Auth\Authenticatable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Auth\Passwords\CanResetPassword;
use Illuminate\Foundation\Auth\Access\Authorizable;
use Illuminate\Contracts\Auth\Authenticatable as AuthenticatableContract;
use Illuminate\Contracts\Auth\Access\Authorizable as AuthorizableContract;
use Illuminate\Contracts\Auth\CanResetPassword as CanResetPasswordContract;
use Illuminate\Database\Eloquent\SoftDeletes;
use Cmgmyr\Messenger\Traits\Messagable;


use Auth;
use Zizaco\Entrust\Traits\EntrustUserTrait;

class User extends Model implements AuthenticatableContract,
                                    AuthorizableContract,
                                    CanResetPasswordContract
{
    use Authenticatable, CanResetPassword, EntrustUserTrait, SoftDeletes, Messagable;

    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'users';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'description',
        'title',
        'password',
        'token',
        'profile_pic',
        'is_confirmed',
        'is_active',
        'account_id',
        'portal_id',
    ];

    /**
     * The attributes excluded from the model's JSON form.
     * @var array
     */
    protected $hidden = [
        'password',
        'tokens',
        'remember_token'
    ];

    
    /**
     * format date with timezone
     * 
     * @return string
     */
    public function getUpdatedAttribute()
    {
        return $this->updated_at->timezone(Auth::user()->portal->timezone);
    }
    /**
     * format date with timezone
     * 
     * @return string
     */
    public function getCreatedAttribute()
    {
        return $this->created_at->timezone(Auth::user()->portal->timezone);
    }

    public function getInitialsAttribute()
    {
        $words = explode(" ", $this->name);
        $acronym = "";

        foreach ($words as $w) {
          $acronym .= $w[0];
        }
        return strtoupper($acronym);
    }


    public function getProfilePicAttribute($value)
    {
        if (empty($value))
        {
            return 'http://dummyimage.com/300x300/f3f3f3/0084ff.png&text='.$this->initials;
        }
        else
        {
            return $value;
        }
    }

    public function getUnreadCountAttribute()
    {
        return $this->messages()->whereNull('read_at')->count();
    }

    public function accountOwner()
    {
        return $this->hasOne('App\Account');
    }

    public function account()
    {
        return $this->belongsTo('App\Account');
    }

    public function portal()
    {
        return $this->belongsTo('App\Portal');
    }
    public function space()
    {
        return $this->belongsTo('App\Space');
    }

    public function reservations()
    {
        return $this->belongsTo('App\Reservation');
    }

    public function portalOwner()
    {
        return $this->hasOne('App\Portal');
    }

    public function notes()
    {
        return $this->hasOne('App\Note');
    }

    public function comments()
    {
        return $this->hasMany('App\Comment');
    }

    public function messages()
    {
        return $this->morphMany('App\Message', 'messageable');
    }

    public function roles()
    {
        return $this->belongsToMany('App\Role');
    }


    /**
     * gets a list of user names with emails
     * @return array list (id => 'name (email)')
     */
    public static function getUserEmailList()
    {
        $users = User::where('portal_id', Auth::user()->portal_id)
            ->get();
        foreach ($users as $key => $user) {
            $users[$key] = $user->name . " (" . $user->email .")";
        }
        return $users;
    }

    /**
     * attaches and removes roles
     * @param  $role name
     * @return
     */
    public function assignRole($role)
    {
    	if (!empty($role))
    	{
    		// if we're assigning a new owner then make the current owner an admin
    		if ($role == 'member_owner' || $role == 'portal_owner')
    		{
                $current_owner = self::find($this->account->user_id);
                \Log::info($current_owner);
    			// update to reassign role
                if (!empty($current_owner))
                {
                    // detach all roles of previous owner
        			$current_owner->detachRoles(Role::all());

                    // reassign the previous owner
        			if ($role == 'member_owner')
        			{
    	    			$current_owner->attachRole(Role::where('name', 'member_admin')->first()->id);
        			}
        			if ($role == 'portal_owner')
        			{
    	    			$current_owner->attachRole(Role::where('name', 'portal_admin')->first()->id);
        			}
                }

                // update to assign this user as owner
                $this->account->user_id = $this->id;
                $this->account->update();
    		}
    		

    		// detaches all roles
    		$this->detachRoles(Role::all());
            // attach the new role to the current user
    		$this->attachRole(Role::where('name', $role)->first()->id);

    		return true;
    	}
    	return false;
    }
}

sample-php-laravel-app/resources/views/users/account_form.blade.php
@include('partials.error_bar')
{!! Form::open(['method' => 'PATCH', 'class' => 'form-horizontal', 'url' => "/admin/users/{$user->id}"]) !!}
{!! Form::select('account_id', $accounts, $user->account_id, ['class' => 'form-control m-b', 'required' => 'required', 'id' => 'select_account', 'placeholder' => 'Select Account']) !!}
<button class="btn btn-primary" type="submit">Assign User to this Account</button>
{!! Form::close() !!}

sample-php-laravel-app/resources/views/users/breadcrumbs.blade.php
<ol class="breadcrumb">
    <li>
        <a href="/">Home</a>
    </li>
    <li>
        <a href="/users">
            Users
        </a>
    </li>
    @if(@$user->name)
    <li class="active">
        <strong>
            {!! $user->name !!}
        </strong>
    </li>
    @endif
</ol>

sample-php-laravel-app/resources/views/users/dashboard.blade.php
@extends('layouts.default')

@section('heading')
<h1>Dashboard</h1>
@endsection

@section('content')


<div class="row">
    <div class="col-lg-12">
        <div class="wrapper wrapper-content animated fadeInUp">

            @if(empty(Auth::user()->portal_id))
            <div class="text-center">
                        
                        <h2>
                            I am a..
                        </h2>
                        <br>
                        <div class="row">
                            <div class="col-sm-6">
                                <a href="/admin/portals/create">
                                    <img src="/img/stock/owner.png" width="100%">
                                </a>
                            </div>
                            <div class="col-sm-6">
                                <a href="/accounts/renter">
                                    <img src="/img/stock/tenant.png" width="100%">
                                </a>
                            </div>
                        </div>
            @else
            {{-- @if(false) --}}
                {{-- dashboard icons --}}
                @foreach(@$dashboards as $dashboard)
                    @if($dashboard->is_dashboard)
                    <div class="col-sm-6 col-md-3">
                        @include('dashboards.icon')
                    </div>
                    @endif

                @endforeach
            @endif
        </div>
    </div>
</div>
@endsection

@section('tail')
@endsection

sample-php-laravel-app/resources/views/users/edit.blade.php
@extends('layouts.default')

@section('heading')
<h1>Users</h1>
@include('users.breadcrumbs')
@endsection

@section('content')
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">

            @include('users.nav')

            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>Edit User</h5>
                    <div class="ibox-tools">
                        @include('users.toggle_activation')
                    </div>
                </div>

                <div class="ibox-content">
                    <h2>Edit User</h2>
                    <p>A User is person who belongs to an Account to have access to the assigned Spaces.</p>
                    @include('partials.error_bar')
                    {!! Form::model(@$user, ['method' => 'PUT', 'url' => "/users/{$user->id}", 'class' => 'form-horizontal', 'files' => true]) !!}
                    <br>
                    {{-- account --}}
                    <div class="form-group">
                        {!! Form::label('name', 'User Full Name', ['class' => 'col-sm-2 control-label']) !!}
                        <div class="col-sm-10">
                            {!! Form::text('name', null, ['class' => 'form-control', 'required' => true]) !!}
                            <small class="text-danger">{{ $errors->first('name') }}</small>
                        </div>
                    </div>

                    <div class="form-group">
                        {!! Form::label('email', 'User Email', ['class' => 'col-sm-2 control-label']) !!}
                        <div class="col-sm-10">
                            {!! Form::text('email', null, ['class' => 'form-control', 'required' => true]) !!}
                            <small class="text-danger">{{ $errors->first('email') }}</small>
                        </div>
                    </div>

                    <div class="form-group">
                        {!! Form::label('profile_pic', 'User Profile Picture', ['class' => 'col-sm-2 control-label']) !!}
                        <div class="col-sm-10">
                            <img src="{!! $user->profile_pic !!}">
                            <span class="help-block m-b-none">This is your profile picture. For best Results, picture should be a jpg, png, or gif file. Dimensions should be at least 300px x 300px. If you don't have a picture, the initials will be used.</span>
                            {!! Form::file('profile_pic', null, ['class' => 'form-control', 'required' => true]) !!}
                            <small class="text-danger">{{ $errors->first('profile_pic') }}</small>
                        </div>
                    </div>

                    {{-- TODO only if user is admin/owner --}}
                    <div class="form-group">
                        {!! Form::label('role', 'Member Type', ['class' => 'col-sm-2 control-label']) !!}
                        <div class="col-sm-10">
                            {!! Form::select('role', $roles, @$user->roles->lists('name')[0], ['class' => 'form-control selectize', 'id' => 'role']) !!}
                            <small class="text-danger">{{ $errors->first('role') }}</small>
                            <small>Admin's have more access and privileges than members.</small>
                        </div>
                    </div>

                    <div class="form-group">
                        {!! Form::label('description', 'About', ['class' => 'col-sm-2 control-label']) !!}
                        <div class="col-sm-10">
                            {!! Form::textarea('description', null, ['class' => 'form-control']) !!}
                            <small class="text-danger">{{ $errors->first('description') }}</small>
                        </div>
                    </div>

                    <div class="hr-line-dashed"></div>
                    {!! Form::hidden('is_active', true) !!}
                    {!! Form::hidden('account_id', Auth::user()->account_id) !!}
                    {!! Form::hidden('portal_id', Auth::user()->portal_id) !!}

                    <div class="form-group">
                        <div class="col-sm-4 col-sm-offset-2">
                            <button class="btn btn-primary" type="submit">Save changes</button>
                            {!! Form::close() !!}
                            {!! Form::open(['route' => ['users.destroy', $user->id]]) !!}
                                {!! Form::hidden('_method', 'DELETE') !!}
                                {!! Form::submit("Delete", ['class' => 'btn btn-danger']) !!}                    
                            {!! Form::close() !!}
                        </div>
                    </div>                    
                </div>
            </div>
        </div>
    </div>
</div>
@stop

@section('tail')

<!-- Steps -->
{!! HTML::script('js/plugins/staps/jquery.steps.min.js'); !!}

<!-- Jquery Validate -->
{!! HTML::script('js/plugins/validate/jquery.validate.min.js'); !!}

{!! HTML::script('js/app/users.edit.js') !!}

@endsection

sample-php-laravel-app/resources/views/users/form.blade.php
<br>
{{-- account --}}
<div class="form-group">
    {!! Form::label('name', 'User Full Name', ['class' => 'col-sm-2 control-label']) !!}
    <div class="col-sm-10">
        {!! Form::text('name', null, ['class' => 'form-control', 'required' => true]) !!}
        <small class="text-danger">{{ $errors->first('name') }}</small>
    </div>
</div>

<div class="form-group">
    {!! Form::label('email', 'User Email', ['class' => 'col-sm-2 control-label']) !!}
    <div class="col-sm-10">
        {!! Form::text('email', null, ['class' => 'form-control', 'required' => true]) !!}
        <small class="text-danger">{{ $errors->first('email') }}</small>
    </div>
</div>

<div class="form-group">
    {!! Form::label('role', 'Member Type', ['class' => 'col-sm-2 control-label']) !!}
    <div class="col-sm-10">
        {!! Form::select('role', $roles, null, ['class' => 'form-control selectize', 'id' => 'role']) !!}
        <small class="text-danger">{{ $errors->first('role') }}</small>
        <small>Admin's have more access and privileges than members.</small>
    </div>
</div>

<div class="form-group">
    {!! Form::label('description', 'About', ['class' => 'col-sm-2 control-label']) !!}
    <div class="col-sm-10">
        {!! Form::textarea('description', null, ['class' => 'form-control']) !!}
        <small class="text-danger">{{ $errors->first('description') }}</small>
    </div>
</div>

<div class="hr-line-dashed"></div>
{!! Form::hidden('is_active', true) !!}
{!! Form::hidden('account_id', Auth::user()->account_id) !!}
{!! Form::hidden('portal_id', Auth::user()->portal_id) !!}

sample-php-laravel-app/resources/views/users/index.blade.php
@extends('layouts.default')

@section('heading')
<h1>Users</h1>
@endsection

@section('content')

<div class="row">
    <div class="col-lg-12">
        <div class="wrapper wrapper-content animated fadeInUp">

            <div class="row">
                @if (!$users->isEmpty())

                @foreach(@$users as $user)
                <div class="col-lg-4">
                    <div class="contact-box">
                        <a href="{!! route('users.show', $user->id) !!}">
                            <div class="col-sm-4">
                                <div class="text-center">
                                   {{--  <img alt="image" class="img-circle m-t-xs img-responsive" src=""> --}}
                                   {{-- TODO initials --}}
                                   {!! HTML::image(@$user->profile_pic, null, ['class' => 'img-circle m-t-xs img-responsive']) !!}
                                    {{-- <div class="m-t-xs font-bold">Graphics designer</div> --}}
                                </div>
                            </div>
                            <div class="col-sm-8">
                                <h3><strong>{!! $user->name !!}</strong></h3>
                                @if (@$user->account_id)
                                <p>
                                    {!! HTML::image($user->account->profile_pic, null, ['class' => 'img-circle img-responsive', 'title data-original-title' => $user->account->name, 'data-placement' => 'top', 'data-toggle' => 'tooltip']) !!}
                                    <i class="fa fa-building"></i>
                                    <a href="{!! route('accounts.show', $user->account_id) !!}" class="btn btn-xs btn-link"> {!! @$user->account->name !!} </a>
                                </p>
                                @else
                                <p>
                                    <br/>
                                    <br/>
                                    <br/>
                                    <br/>
                                </p>
                                @endif
                                <address>
                                    {{-- space address --}}
                                    <abbr title="Email">E:</abbr> {!! $user->email !!}
                                </address>
                                <div class="pull-right">
                                    <a href="{!! route('users.edit', $user->id) !!}" class="btn btn-xs btn-link"> edit </a> </div>
                                </div>
                            <div class="clearfix"></div>
                        </a>
                    </div>

                </div>
                @endforeach
                @else

                @endif
                
            </div>
        </div>
    </div>
</div>
@stop

@section('tail')

<!-- Steps -->
{!! HTML::script('js/plugins/staps/jquery.steps.min.js'); !!}

<!-- Jquery Validate -->
{!! HTML::script('js/plugins/validate/jquery.validate.min.js'); !!}

<script type="text/javascript">
    $('.img-circle').tooltip();
</script>

@endsection

sample-php-laravel-app/resources/views/users/invite.blade.php
@extends('layouts.preauth')

@section('content')

<form class="form-horizontal m-t" role="form" method="POST" action="{{ url('/password/reset') }}">
	{!! csrf_field() !!}
	<input type="hidden" name="token" value="{{ $token }}">

	<div class="form-group">
		<label class="col-md-4 control-label">Password</label>
		<div class="col-md-8">
			<input type="password" class="form-control" name="password">
		</div>
	</div>

	<div class="form-group">
		<label class="col-md-4 control-label">Confirm Password</label>
		<div class="col-md-8">
			<input type="password" class="form-control" name="password_confirmation">
		</div>
	</div>

	<div class="form-group">
		<div class="col-md-8 col-md-offset-4">
			<button type="submit" class="btn btn-primary">
				Continue
			</button>
		</div>
	</div>
</form>
				
@endsection

sample-php-laravel-app/resources/views/users/invited.blade.php
@extends('layouts.preauth')

@section('content')

<h3>Set Password</h3>
<form class="form-horizontal m-t" role="form" method="POST" action="{{ url('/users/invited/' . $token) }}">
	{!! csrf_field() !!}
	<div class="form-group">
		<label class="col-md-4 control-label">Password</label>
		<div class="col-md-8">
			<input type="password" class="form-control" name="password">
		</div>
	</div>

	<div class="form-group">
		<label class="col-md-4 control-label">Confirm Password</label>
		<div class="col-md-8">
			<input type="password" class="form-control" name="password_confirmation">
		</div>
	</div>

	<div class="form-group">
		<div class="col-md-8 col-md-offset-4">
			<button type="submit" class="btn btn-primary">
				Continue
			</button>
		</div>
	</div>
</form>
				
@endsection

sample-php-laravel-app/resources/views/users/nav.blade.php
<ul class="nav nav-pills nav-justified ibox-nav">
    {{-- user basics --}}
    <li class="{!! (Request::segments()[0] == 'users' && Request::segments()[2] == 'edit')? 'active' : null ; !!}">
        <a href="#">Edit User</a>
    </li>

</ul>
<br/>

sample-php-laravel-app/resources/views/users/profile.blade.php
<div class="col-md-3">
    <div class="ibox float-e-margins">
        <div>
            <div class="ibox-content no-padding border-left-right">
                {!! HTML::image(@$user->profile_pic, null, ['class' => 'img-responsive']) !!}
            </div>
            <div class="ibox-content profile-content">
                <h2>
                <strong>{!! @$user->name !!}</strong>
                </h2>
                @if (!empty($user->account_id))
                <h5>
                <a href="{!! route('accounts.show', @$user->account_id) !!}" class="btn btn-xs btn-link">
                    {!! HTML::image(@$user->account->profile_pic, null, ['class' => 'img-circle img-responsive', 'width' => '100%']) !!}
                    {!! @$user->account->name !!}
                </a>
                </h5>
                @endif
                @if ($user->description)
                <h5>
                About
                </h5>
                <p>
                    {!! @$user->description !!}
                </p>
                @endif
                <div class="user-button">
                    <div class="row">
                        <div class="col-md-12">
                            <a href="#message" class="btn btn-primary btn-sm btn-block" id="private_message" onclick="$('#private-message-modal').modal();"><i class="fa fa-envelope"></i> Send Private Message</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>